/**
 * Bundles the Crash board test suite for jsdom.
 *
 *   node tests/crash-board/build.mjs && node tests/crash-board/runner.cjs
 *
 * Three things are swapped out on the way in:
 *   • the HTTP layer (`services/api`) for a scriptable stub,
 *   • the auth + toast providers for stubs with stable identities,
 *   • every `*.module.css` for a proxy that resolves `styles.foo` to the
 *     `css-foo` class name (jsdom does not need the real stylesheet — the
 *     suite reads class names and inline styles; the stylesheet itself is
 *     asserted separately, straight from disk).
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const p = (...s) => resolve(here, ...s);

const stubPlugin = {
  name: 'crash-board-test-stubs',
  setup(b) {
    b.onResolve({ filter: /[/\\]services[/\\]api$/ }, () => ({ path: p('../stubs/gamesApi.js') }));
    b.onResolve({ filter: /[/\\]context[/\\]AuthContext$/ }, () => ({ path: p('../stubs/authContext.jsx') }));
    b.onResolve({ filter: /[/\\]context[/\\]ToastContext$/ }, () => ({ path: p('../stubs/toastContext.jsx') }));

    // Sound files -> a stable fake path ("asset://crash/Win.mp3") so tests can
    // assert WHICH sound a game fired without loading real audio.
    b.onResolve({ filter: /\.mp3$/ }, (args) => ({ path: args.path, namespace: 'audio-stub' }));
    b.onLoad({ filter: /.*/, namespace: 'audio-stub' }, (args) => {
      const tail = args.path.split(/[/\\]/).slice(-2).join('/');
      return { loader: 'js', contents: `export default ${JSON.stringify('asset://' + tail)};` };
    });

    // CSS modules -> class-name proxy
    b.onResolve({ filter: /\.module\.css$/ }, (args) => ({ path: args.path, namespace: 'css-module-stub' }));
    b.onLoad({ filter: /.*/, namespace: 'css-module-stub' }, () => ({
      loader: 'js',
      contents: `
        const hit = (key) => 'css-' + key;           // css-tipMarker, css-yTickBox …
        export default new Proxy({}, { get: (_t, key) => hit(String(key)) });
      `,
    }));
  },
};

await build({
  entryPoints: [p('uitest.jsx')],
  outfile: p('dist/uitest.cjs'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  jsx: 'automatic',
  // every asset a game can import (mp3 = a fake path; the tests stub Audio)
  loader: { '.webp': 'dataurl', '.gif': 'dataurl', '.jpg': 'dataurl', '.png': 'dataurl', '.svg': 'text', '.mp3': 'text', '.mp4': 'text' },
  define: {
    'process.env.NODE_ENV': '"test"',
    __TEST_DIR__: JSON.stringify(here),   // import.meta is not usable in cjs output
  },
  plugins: [stubPlugin],
  logLevel: 'warning',
  banner: { js: '/* generated by tests/crash-board/build.mjs — do not edit */' },
});

console.log('built tests/crash-board/dist/uitest.cjs');
