/**
 * Bundles the site-wide UI suite (`tests/site-ui/uitest.jsx`) for jsdom.
 *
 * Unlike the board suite, the TOAST PROVIDER IS REAL here — the "Loss" toast is
 * part of what is being tested — while the HTTP layer and auth are stubbed.
 *
 *   node tests/site-ui/build.mjs && node tests/site-ui/runner.cjs
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const p = (...s) => resolve(here, ...s);

const stubPlugin = {
  name: 'site-ui-test-stubs',
  setup(b) {
    b.onResolve({ filter: /[/\\]services[/\\]api$/ }, () => ({ path: p('../stubs/gamesApi.js') }));
    b.onResolve({ filter: /[/\\]context[/\\]AuthContext$/ }, () => ({ path: p('../stubs/authContext.jsx') }));

    b.onResolve({ filter: /\.module\.css$/ }, (args) => ({ path: args.path, namespace: 'css-module-stub' }));
    b.onLoad({ filter: /.*/, namespace: 'css-module-stub' }, () => ({
      loader: 'js',
      contents: `export default new Proxy({}, { get: (_t, key) => 'css-' + String(key) });`,
    }));
  },
};

await build({
  entryPoints: [p('uitest.jsx')],
  outfile: p('dist/uitest.cjs'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  jsx: 'automatic',
  loader: {
    '.webp': 'dataurl', '.gif': 'dataurl', '.jpg': 'dataurl', '.jpeg': 'dataurl', '.png': 'dataurl',
    '.svg': 'text', '.mp3': 'dataurl', '.wav': 'dataurl', '.ogg': 'dataurl', '.mp4': 'dataurl',
  },
  define: { 'process.env.NODE_ENV': '"test"', __TEST_DIR__: JSON.stringify(here) },
  plugins: [stubPlugin],
  logLevel: 'warning',
  banner: { js: '/* generated by tests/site-ui/build.mjs — do not edit */' },
});

console.log('built tests/site-ui/dist/uitest.cjs');
